// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1FNTNdjJqQr-fT5n0HK6W4lKS0i_M4K4',
    appId: '1:810724121400:web:ccb3dd66587b75dcb27fcd',
    messagingSenderId: '810724121400',
    projectId: 'chat-app-6c4a0',
    authDomain: 'chat-app-6c4a0.firebaseapp.com',
    storageBucket: 'chat-app-6c4a0.appspot.com',
    measurementId: 'G-C09LX7H60P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EzLN4y2q9DlgM022yIp-fjf8fD3px_Y',
    appId: '1:810724121400:android:a71da79ac3386a23b27fcd',
    messagingSenderId: '810724121400',
    projectId: 'chat-app-6c4a0',
    storageBucket: 'chat-app-6c4a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1DZonzt_K-iG0Z1NzVNTvW97LVvmoAo',
    appId: '1:810724121400:ios:a76a0b36f01ba990b27fcd',
    messagingSenderId: '810724121400',
    projectId: 'chat-app-6c4a0',
    storageBucket: 'chat-app-6c4a0.appspot.com',
    iosClientId: '810724121400-bdfi9tndkr48dricp85lujkg524vhe82.apps.googleusercontent.com',
    iosBundleId: 'com.example.testweather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA1DZonzt_K-iG0Z1NzVNTvW97LVvmoAo',
    appId: '1:810724121400:ios:70e9337cf3671f33b27fcd',
    messagingSenderId: '810724121400',
    projectId: 'chat-app-6c4a0',
    storageBucket: 'chat-app-6c4a0.appspot.com',
    iosClientId: '810724121400-jg4psrad975u7q03njldoah6cij49er0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testweather.RunnerTests',
  );
}
